/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ca44953263191a5c5920947f41dcf63f)
interface __BaseEnv_Env {
	CONTACT_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
