/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9e733127588f385c231438d71c47abd7)
interface __BaseEnv_Env {
	CONTACT_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
